<a href="https://colab.research.google.com/github/vitor-007/APM-turma5/blob/main/vitorreina_ConsumoAPI0915.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pipeline de Análise de Dados [API - Churn]

## Importação de Bibliotecas

*   Pandas
*   Numpy
*   MatPlotLib
*   SeaBorn

In [4]:
!pip install pandas
!pip install numpy
!pip install matplotlib
!pip install seaborn
!pip install scikit-learn

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (2.1.3)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.13/dist-packages (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (1.5.1)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (2.1.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.13/dist-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /usr/local/lib/python3.13/dist-packages (from seaborn) (2.1.3)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.13/dist-packages (from seaborn) (2.2.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /usr/local/lib/python3.13/dist-packages (from seaborn) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.13/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.2->seaborn) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.13/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.13/dist-packages (from scikit-learn) (2.1.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.2.0->scikit-learn) (3.1.2)

In [5]:
import pandas as pd # organiza arrays
import numpy as np # calculos complexos
import matplotlib.pyplot as plt # poder ver execuções matematicas complexas
import seaborn as sns # visualização de dados
import plotly.express as px # expor dados via api

In [6]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).

## Alpha Vantage API

In [10]:
import requests

API_KEY = 'EFBHA2DQDBFS0WK0'
EMPRESA = 'NFLX'

url = f'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol={EMPRESA}&apikey={API_KEY}'
response = requests.get(url)
dia_netflix = response.json()
base_dia_netflix = pd.DataFrame(dia_netflix['Time Series (Daily)']).T
base_dia_netflix

            1. open  2. high   3. low 4. close 5. volume
2026-09-14  78.9700  81.0200  78.4900  80.3200  30945111
2026-09-11  76.6400  77.5661  76.1500  77.4000  22237769
2026-09-10  75.3250  76.3000  75.0300  76.0100  20049027
2026-09-09  76.3400  76.7200  75.8700  76.0300  22779615
2026-09-08  77.5500  77.7300  75.9200  76.7700  33865470
...             ...      ...      ...      ...       ...
2026-04-28  91.5000  92.3400  90.0200  92.2700  33418126
2026-04-27  92.0500  92.8400  91.3000  91.3700  29707439
2026-04-24  92.5700  93.2800  91.8000  92.4400  32553177
2026-04-23  94.0600  94.6400  92.0730  92.8200  36851674
2026-04-22  93.0600  93.8500  92.7700  93.2400  33694345

[100 rows x 5 columns]

In [9]:
EMPRESA = 'NVDA'

url = f'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol={EMPRESA}&apikey={API_KEY}'
response = requests.get(url)
dia_netflix = response.json()
base_dia_netflix = pd.DataFrame(dia_netflix['Time Series (Daily)']).T
base_dia_netflix

             1. open   2. high    3. low  4. close  5. volume
2026-09-14  211.2400  212.7700  208.9300  210.9600  132267244
2026-09-11  221.2350  222.0000  218.1500  218.2900   89060140
2026-09-10  220.5250  220.9900  217.2000  218.3600  105768001
2026-09-09  225.2750  226.1800  223.4600  223.6700   82955478
2026-09-08  233.1100  233.7100  224.8500  225.7300  122965555
...              ...       ...       ...       ...        ...
2026-04-28  209.4900  214.7300  208.2000  213.1700  180275363
2026-04-27  209.6450  216.8250  207.3800  216.6100  187172421
2026-04-24  199.9600  210.9500  199.8100  208.2700  214134441
2026-04-23  202.4600  203.8290  197.2206  199.6400  113561830
2026-04-22  200.9900  202.5000  199.0000  202.5000  107501042

[100 rows x 5 columns]

## Valorant API

In [ ]:
url = f'https://valorant-api.com/v1/agents'
response = requests.get(url)
lista_agente = response.json()
lista_agente
base_agentes = pd.DataFrame(lista_agente['data'])
base_agentes

In [20]:
AGENTE = base_agentes.loc[base_agentes['displayName'] == 'Sova', 'uuid'].values[0]

url = f'https://valorant-api.com/v1/agents/{AGENTE}'
response = requests.get(url)
status_sova = response.json()
status_sova = pd.DataFrame([status_sova['data']])
status_sova

,uuid,displayName,description,developerName,releaseDate,characterTags,displayIcon,displayIconSmall,bustPortrait,fullPortrait,...,backgroundGradientColors,assetPath,isFullPortraitRightFacing,isPlayableCharacter,isAvailableForTest,isBaseContent,role,recruitmentData,abilities,voiceLine
0,320b2a48-4d9b-a075-30f1-1f93a9b638fa,Sova,Born from the eternal winter of Russia's tundr...,Hunter,1970-01-01T00:00:00Z,"[Detection, Area Damage]",https://media.valorant-api.com/agents/320b2a48...,https://media.valorant-api.com/agents/320b2a48...,https://media.valorant-api.com/agents/320b2a48...,https://media.valorant-api.com/agents/320b2a48...,...,"[355285ff, 0f1923ff, 101c47ff, 0f192300]",ShooterGame/Content/Characters/Hunter/Hunter_P...,False,True,True,True,{'uuid': '1b47567f-8f7b-444b-aae3-b0c634622d10...,None,"[{'slot': 'Ability1', 'displayName': 'Shock Bo...",None